### ISSUE TITLE
Adding a string of html under player

### ISSUE THREAD

**Issue by jdcauley** [bfncs/jQuery-Youtube-Channel-Player#2]
I'm less than a novice when it comes to js.  

How could I add a string of html under the main player?

Thanks for your time.

Jordan

**Comment by bfncs** [comment]
Hi Jordan,

there is no templating or something similiar included in the plugin.
Have a look at [Line 104](https://github.com/boundaryfunctions/jQuery-Youtube-Channel-Player/blob/master/jquery.ytChanPlayer.js#L104) of `jquery.ytChanPlayer.js` and the stuff around it. This is where the list items markup is generated.  You might copy my code and add a line to append your HTML to the DOM somewhere around these lines.

Probably I should use some kind of templating language for the markup here... might take me some time though. I hope that this helps you to get where you want.

**Comment by jdcauley** [comment]
Hi Marc,

A friend of mine gave me a hand with this.  I got what I need with this via:

<script>
  (function ($) {
    $(document).ready(function () {
      var playerDiv = $("#ytChanPlayer");
      playerDiv.ytChanPlayer({
        username: 'soundasthma',
        maxResults: 6,
        sticky: 'EwHXRPOLnAg'
      }); 
       $("ul.yt-channel-list").before("<p class='tagline'>Well, it seems that people are having a lot of fun putting together their videos. Go ahead and submit your video to be the first! Don't forget, you are taking the first step to winning an iPad by submitting.</p>") 
    });
  }(jQuery));
</script>

My use of your channel player can be found at http://videos.soundasthma.com

Thanks for getting back to me though.

Jordan

**Comment by bfncs** [comment]
Ah great if this works for you! I was thinking of having some dynamic markup there, like the current video's title, length, etc.

Thanks for showing, where you use it! :-)

**Comment by jdcauley** [comment]
I think some templating would be great.  I'm no js developer or I'd give you hand but I can tell you what kinds of things I wish I could have done with it.  Let me know if I can do anything for you
